-- Seed SBA lenders from CSV

INSERT INTO lenders_sba (
  lender_name,
  website,
  contact_person,
  phone,
  email,
  submission_docs,
  submission_type,
  submission_process,
  timeline,
  states_available,
  products_offered,
  minimum_loan_amount,
  max_loan_amount,
  use_of_funds,
  credit_requirement,
  preferred_industries,
  industry_restrictions,
  google_drive,
  note,
  status
) VALUES
-- US Bank
(
  'US Bank',
  'Link',
  'Tyler Ryan',
  'Tyler Cell: 847-804-4301',
  'tyler.ryan@usbank.com',
  '1. 3 Years Business Tax Return (all pages) (extension for year if they are not filed)
2. 3 Years Personal Tax Returns
3. Debt Schedule
4. YTD Financials ("Cash Basis" P&L and Balance Sheet)
5. Personal Financial Statement',
  'Email',
  'Send the full package of submission docs to tyler and cc Shawn Hamilton + The Deals Email shawn.hamilton@usbank.com and deals@hugecapitalfunding.com',
  '7 Days For Term Sheet, 30-45 Days of Credit and 30-45 Days of Closing',
  '50 (If No Footprint Need Credit Card or Real Estate)',
  'SBA 7(a), 504 and Express LOC',
  '$300,000',
  '$5,000,000',
  'Business Acquisition, Working Capital, Partner Buyouts, Debt Refinance and Equipment',
  640,
  'Non Franchise Restauraunts and Hospitality/Construction',
  'Must Be Backed w/ Colleteral',
  'Google Drive',
  '',
  'active'
),
-- Huntington Bank
(
  'Huntington Bank',
  'Link',
  'Scott Asbury',
  'Scott Cell: 832-428-4813',
  'scott.asbury@huntington.com',
  'Personal: 1. Three years personal tax returns, 2. Huntington Bank Personal Financial Statement, 3. Resume, 4. YTD 2025 pay stub, 5. Copy of Government/State issued ID. Business: 1. Three years corporate tax returns, 2. Interim financials, 3. Business debt schedule, 4. K1s, 5. Projections. III. Business plan Questionnaire. IV. Purchase agreement / LOI',
  'Email',
  'Send Full Package to scott and CC Deals Email.',
  '7 Days For Term Sheet, 30-45 Days of Credit and 30-45 Days of Closing',
  '50',
  'SBA 7(a), 504 and Express LOC',
  '$300,000',
  '$5,000,000',
  'Business Acquisition, Working Capital, Partner Buyouts, Debt Refinance, Start-Ups and Equipment',
  680,
  '',
  '',
  'Google Drive',
  '',
  'active'
),
-- Credit Bench/Bayfirst
(
  'Credit Bench/Bayfirst',
  'Link',
  'Luis Garcia',
  'Luis Cell: 305-783-8413',
  'luis.garcia@bayfirstfinancial.com',
  '1. Driver''s Licenses of all owners with 20%+ stake, 2. 2022-2024 business tax returns, 3. Interim 2025 P&L and Balance Sheet, 4. Business Debt Schedule, 5. 2022-2024 personal taxes for owners with 20%+ stake, 6. Personal Financial Statement, 7. Last 6 months of business bank statements, 8. Use of Proceeds template',
  'Email',
  'Send Full package to Luis and CC Deals Email.',
  '7 Days For Term Sheet, 30-45 Days of Credit and 30-45 Days of Closing',
  '50',
  'SBA 7(a), 504',
  '$50,000',
  '$5,000,000',
  'Business Acquisition, Working Capital, Partner Buyouts, Debt Refinance, Start-Ups and Equipment',
  720,
  'Transportation, Warehousing, Food Services, Hotels, Advertising and Consulting Services',
  '',
  'Google Drive',
  '',
  'active'
),
-- CDC Loans
(
  'CDC Loans',
  'Link',
  'Miriam Torres Baltys',
  'Miriams Cell: 619-414-0030',
  'mbaltys@cdcloans.com',
  '1. 2 Years of most current business tax returns, 2. 1 Year of most current personal tax returns, 3. 2023 & 2024 Profit & Loss Statement and Balance Sheet (YTD), 4. Business Debt Schedule, 5. Application, 6. Personal Financial Statement, 7. Current pay stub, 8. 6 months of business bank statements, 9. month of personal bank statements or liquid assets',
  'Online Portal',
  '1. Create an Account Here - https://files.cdcloans.com/, 2. When Submitting - All information inputted is for the owner(s)',
  '7 Days For Term Sheet, 30-45 Days of Credit and 30-45 Days of Closing',
  '50 (Primary Footprint CA, AZ, NV + Metro Dallas, Washington DC, Miami, Detroit and Atlanta)',
  'SBA 7(a) and 504',
  '$30,000',
  '$350,000',
  'Business Acquisition, Working Capital, Partner Buyouts, Debt Refinance, Start-Ups and Equipment',
  NULL,
  'Restaurants, Coffee Shops, Bars, Adult Stores, Marijuana, Logistics and Trucking',
  '',
  'Google Drive',
  '',
  'active'
),
-- Integro Bank
(
  'Integro Bank',
  'Link',
  'Travis Corrow',
  'Travis''s Cell: 602-777-1361',
  'travis.corrow@integro.bank',
  '',
  '',
  '',
  '',
  '50 (Prefers AZ, NV, CA)',
  '',
  '$100,000',
  '$5,000,000',
  '',
  660,
  '',
  '',
  'Google Drive',
  '',
  'active'
),
-- SmartBiz
(
  'SmartBiz',
  'Link',
  'Tyler Leninger',
  'Tyler''s Cell: 512-893-7355',
  'tyler.leninger@smartbizloans.com',
  '1. 3 Years Business Tax Return, 2. 3 Years Personal Tax Returns, 3. Debt Schedule, 4. YTD Financials, 5. 6 Months Bank Statements',
  'Online Portal',
  '1. Login Here - https://smartbizbank.com/assist/session/new, 2. Our Use Referral Link - https://smartbizloans.com/assist/partner/hugecapital/deals',
  'Traditional Can Close in as Little as 30, 24-48 hours for soft offer. Bolt can close in a week',
  '50',
  'SBA Bolt and 7(a)',
  '$50,000',
  '$350,000',
  'Working Capital, Debt Refinancince and Equipment',
  660,
  '',
  'Transportation, Logistics, Most Construction, Adult Stores, Marijuana and Real Estate',
  'Google Drive',
  '',
  'active'
),
-- Live Oak Express
(
  'Live Oak Express',
  'Link',
  'Tyler Quin',
  'Tyler''s Cell: 540-797-2143',
  'tyler.quinn@liveoak.bank',
  '1. 3 Years Business Tax Return, 2. 3 Years Personal Tax Returns, 3. Debt Schedule, 4. YTD Financials, 5. 3 Months Bank Statements',
  'Email',
  '1. Send Email to express@liveoak.bank + tyler.quinn@liveoak.bank, 2. Answer Questions: Loan Amount, Industry, Loan Purpose, Timeline, Location, Positive Cash Flow',
  'Express $350k in below averages 17-20 Days For Closing',
  '50',
  'SBA 7(a)',
  '$10,000',
  '$350,000',
  'Working Capital, Refinances, Equipment, Business Acquisitions, Leasehold Improvements, Start-ups',
  650,
  'Accounting & Tax, Agriculture, Auto Dealerships, Automotive Care, Broadband, Dental, Educational Services, Fitness Centers, Franchise Restaurants, Franchises, Funeral Home and Crematory, Government Contracting, Hardware Stores, Healthcare, Home Care, HVAC and Plumbing, Insurance, Investment Advisory, Law Firms, Managed Service Providers, Pet Care Facilities, Pharmacy, Professional Services Firms, Property Management, Restoration, RV Parks, Self-Storage, Veterinary',
  'Landscaping/Lawn Care, Gambling, Marijuana, Shooting Ranges, Firearms, Gentleman''s clubs, Check Cashing, Pawn Shops, Real estate, Art Galleries, Gas Stations, Online Trading, Golf Courses, Non-MD owned medical practices, Co-working franchises, Trucking, Emergency Rooms, Vape/Smoke/Cigar/Tobacco, Construction, Wholesale, Ecommerce',
  'Google Drive',
  '',
  'active'
);
