export interface McaLender {
  id: string;
  lender_name: string;
  paper: string | null;
  website: string | null;
  iso_rep: string | null;
  phone: string | null;
  email: string | null;
  submission_docs: string | null;
  submission_type: string | null;
  submission_process: string | null;
  minimum_credit_requirement: number | null;
  minimum_monthly_revenue: string | null;
  max_nsf_negative_days: string | null;
  minimum_daily_balances: string | null;
  minimum_time_in_business: string | null;
  minimum_loan_amount: string | null;
  max_loan_amount: string | null;
  terms: string | null;
  positions: string | null;
  buyouts: string | null;
  products_offered: string | null;
  states_restrictions: string | null;
  preferred_industries: string | null;
  restricted_industries: string | null;
  google_drive: string | null;
  note: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
  status: 'active' | 'inactive' | 'pending' | 'archived';
}

export interface McaLenderFormData {
  lender_name: string;
  paper?: string;
  website?: string;
  iso_rep?: string;
  phone?: string;
  email?: string;
  submission_docs?: string;
  submission_type?: string;
  submission_process?: string;
  minimum_credit_requirement?: number;
  minimum_monthly_revenue?: string;
  max_nsf_negative_days?: string;
  minimum_daily_balances?: string;
  minimum_time_in_business?: string;
  minimum_loan_amount?: string;
  max_loan_amount?: string;
  terms?: string;
  positions?: string;
  buyouts?: string;
  products_offered?: string;
  states_restrictions?: string;
  preferred_industries?: string;
  restricted_industries?: string;
  google_drive?: string;
  note?: string;
  status: 'active' | 'inactive' | 'pending' | 'archived';
}
