// Lender Type Registry - Central Configuration for all 11 lender types
// This file is the single source of truth for lender type definitions
import type { LenderTypeSchema, FieldDefinition } from '../types/schema';

// ============================================================================
// SHARED FIELD DEFINITIONS
// ============================================================================

const commonContactFields: FieldDefinition[] = [
  {
    id: 'lender_name',
    dbColumnName: 'lender_name',
    displayName: 'Lender Name',
    type: 'text',
    required: true,
    category: 'contact',
    visible: true,
    displayInTable: true,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Lender Name',
  },
  {
    id: 'contact_person',
    dbColumnName: 'contact_person',
    displayName: 'Contact Person',
    type: 'text',
    category: 'contact',
    visible: true,
    displayInTable: true,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Contact Person',
  },
  {
    id: 'phone',
    dbColumnName: 'phone',
    displayName: 'Phone',
    type: 'phone',
    category: 'contact',
    visible: true,
    displayInTable: true,
    displayInExpanded: true,
    searchable: false,
    csvHeader: 'Phone',
  },
  {
    id: 'email',
    dbColumnName: 'email',
    displayName: 'Email',
    type: 'email',
    category: 'contact',
    visible: true,
    displayInTable: true,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Email',
  },
  {
    id: 'website',
    dbColumnName: 'website',
    displayName: 'Website',
    type: 'url',
    category: 'links',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: false,
    csvHeader: 'Website',
  },
];

const commonLoanFields: FieldDefinition[] = [
  {
    id: 'min_loan_amount',
    dbColumnName: 'min_loan_amount',
    displayName: 'Min Loan Amount',
    type: 'currency',
    category: 'requirements',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Min Loan Amount',
  },
  {
    id: 'max_loan_amount',
    dbColumnName: 'max_loan_amount',
    displayName: 'Max Loan Amount',
    type: 'currency',
    category: 'requirements',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Max Loan Amount',
  },
  {
    id: 'credit_requirement',
    dbColumnName: 'credit_requirement',
    displayName: 'Credit Requirement',
    type: 'text',
    category: 'requirements',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Credit Requirement',
  },
];

const commonRestrictionFields: FieldDefinition[] = [
  {
    id: 'preferred_industries',
    dbColumnName: 'preferred_industries',
    displayName: 'Preferred Industries',
    type: 'textarea',
    category: 'restrictions',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Preferred Industries',
  },
  {
    id: 'restricted_industries',
    dbColumnName: 'restricted_industries',
    displayName: 'Restricted Industries',
    type: 'textarea',
    category: 'restrictions',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Industy Restrictions',
  },
];

const commonLinksFields: FieldDefinition[] = [
  {
    id: 'drive_link',
    dbColumnName: 'drive_link',
    displayName: 'Google Drive Link',
    type: 'url',
    category: 'links',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: false,
    csvHeader: 'Drive Link',
  },
  {
    id: 'notes',
    dbColumnName: 'notes',
    displayName: 'Notes',
    type: 'textarea',
    category: 'other',
    visible: true,
    displayInTable: false,
    displayInExpanded: true,
    searchable: true,
    csvHeader: 'Note',
  },
];

// ============================================================================
// LENDER TYPE SCHEMAS - 11 TYPES
// ============================================================================

export const BUSINESS_LINE_OF_CREDIT: LenderTypeSchema = {
  id: 'business-line-of-credit',
  displayName: 'Business Line of Credit',
  description: 'Traditional bank and non-bank business lines of credit',
  category: 'basic',
  tableName: 'lenders_business_line_of_credit',
  fields: [
    ...commonContactFields,
    {
      id: 'bank_non_bank',
      dbColumnName: 'bank_non_bank',
      displayName: 'Bank / Non-Bank',
      type: 'select',
      category: 'contact',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      options: [
        { value: 'Bank', label: 'Bank' },
        { value: 'Non-Bank', label: 'Non-Bank' },
      ],
    },
    {
      id: 'iso_contacts',
      dbColumnName: 'iso_contacts',
      displayName: 'ISO Contacts',
      type: 'text',
      category: 'contact',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonLoanFields,
    {
      id: 'credit_used',
      dbColumnName: 'credit_used',
      displayName: 'Credit Used',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'min_time_in_business',
      dbColumnName: 'min_time_in_business',
      displayName: 'Min Time in Business',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'minimum_deposit_count',
      dbColumnName: 'minimum_deposit_count',
      displayName: 'Minimum Deposit Count',
      type: 'number',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
    },
    {
      id: 'min_monthly_revenue_amount',
      dbColumnName: 'min_monthly_revenue_amount',
      displayName: 'Min Monthly Revenue Amount',
      type: 'currency',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'min_avg_daily_balance',
      dbColumnName: 'min_avg_daily_balance',
      displayName: 'Min Avg Daily Balance',
      type: 'currency',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'max_loan',
      dbColumnName: 'max_loan',
      displayName: 'Max Loan',
      type: 'currency',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'positions',
      dbColumnName: 'positions',
      displayName: 'Positions',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'terms',
      dbColumnName: 'terms',
      displayName: 'Terms',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'payments',
      dbColumnName: 'payments',
      displayName: 'Payments',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'draw_fees',
      dbColumnName: 'draw_fees',
      displayName: 'Draw Fees',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonRestrictionFields,
    {
      id: 'ineligible_states',
      dbColumnName: 'ineligible_states',
      displayName: 'Ineligible States',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_docs',
      dbColumnName: 'submission_docs',
      displayName: 'Submission Docs',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_type',
      dbColumnName: 'submission_type',
      displayName: 'Submission Type',
      type: 'text',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['max_loan', 'credit_requirement', 'terms', 'products_offered', 'website', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Bank Non Bank': 'bank_non_bank',
    'ISO Contacts': 'iso_contacts',
    'Phone': 'phone',
    'Email': 'email',
    'Credit Requirement': 'credit_requirement',
    'Credit Used': 'credit_used',
    'Min Time In Business': 'min_time_in_business',
    'Minimum Deposit Count': 'minimum_deposit_count',
    'Min Monthly Revenue Amount': 'min_monthly_revenue_amount',
    'Min Avg Daily Balance': 'min_avg_daily_balance',
    'Max Loan': 'max_loan',
    'Positions': 'positions',
    'Products Offered': 'products_offered',
    'Terms': 'terms',
    'Payments': 'payments',
    'Draw Fees': 'draw_fees',
    'Preferred Industries': 'preferred_industries',
    'Restricted Industries': 'restricted_industries',
    'Ineligible States': 'ineligible_states',
    'Submission Docs': 'submission_docs',
    'Submission Type': 'submission_type',
    'Submission Process': 'submission_process',
    'Drive Link': 'drive_link',
    'Website': 'website',
    'Notes': 'notes',
  },
};

export const MCA: LenderTypeSchema = {
  id: 'mca',
  displayName: 'MCA',
  description: 'Merchant Cash Advance providers',
  category: 'basic',
  tableName: 'lenders_mca',
  fields: [
    ...commonContactFields,
    {
      id: 'paper',
      dbColumnName: 'paper',
      displayName: 'Paper',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'iso_rep',
      dbColumnName: 'iso_rep',
      displayName: 'ISO Rep',
      type: 'text',
      category: 'contact',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_docs',
      dbColumnName: 'submission_docs',
      displayName: 'Submission Docs',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_type',
      dbColumnName: 'submission_type',
      displayName: 'Submission Type',
      type: 'text',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'minimum_credit_requirement',
      dbColumnName: 'minimum_credit_requirement',
      displayName: 'Minimum Credit Requirement',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'minimum_monthly_revenue',
      dbColumnName: 'minimum_monthly_revenue',
      displayName: 'Minimum Monthly Revenue',
      type: 'currency',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'max_nsf_negative_days',
      dbColumnName: 'max_nsf_negative_days',
      displayName: 'Max NSF/Negative Days',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'minimum_daily_balances',
      dbColumnName: 'minimum_daily_balances',
      displayName: 'Minimum Daily Balances',
      type: 'currency',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'minimum_time_in_business',
      dbColumnName: 'minimum_time_in_business',
      displayName: 'Minimum Time in Business',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonLoanFields.slice(0, 2), // min and max loan amount
    {
      id: 'terms',
      dbColumnName: 'terms',
      displayName: 'Terms',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'positions',
      dbColumnName: 'positions',
      displayName: 'Positions',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'buyouts',
      dbColumnName: 'buyouts',
      displayName: 'Buyouts',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'states_restrictions',
      dbColumnName: 'states_restrictions',
      displayName: 'States Restrictions',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonRestrictionFields,
    {
      id: 'portal_url',
      dbColumnName: 'portal_url',
      displayName: 'Portal URL',
      type: 'url',
      category: 'links',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
    },
    {
      id: 'preferred_industries_doc_link',
      dbColumnName: 'preferred_industries_doc_link',
      displayName: 'Preferred Industries Doc Link',
      type: 'url',
      category: 'links',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
    },
    {
      id: 'restricted_industries_doc_link',
      dbColumnName: 'restricted_industries_doc_link',
      displayName: 'Restricted Industries Doc Link',
      type: 'url',
      category: 'links',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['minimum_monthly_revenue', 'terms', 'products_offered', 'minimum_credit_requirement', 'portal_url', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Paper': 'paper',
    'ISO Rep': 'iso_rep',
    'Phone': 'phone',
    'Email': 'email',
    'Website': 'website',
    'Submission Docs': 'submission_docs',
    'Submission Type': 'submission_type',
    'Submission Process': 'submission_process',
    'Minimum Credit Requirement': 'minimum_credit_requirement',
    'Minimum Monthly Revenue': 'minimum_monthly_revenue',
    'Max NSF Negative Days': 'max_nsf_negative_days',
    'Minimum Daily Balances': 'minimum_daily_balances',
    'Minimum Time In Business': 'minimum_time_in_business',
    'Minimum Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Terms': 'terms',
    'Positions': 'positions',
    'Buyouts': 'buyouts',
    'Products Offered': 'products_offered',
    'States Restrictions': 'states_restrictions',
    'Preferred Industries': 'preferred_industries',
    'Restricted Industries': 'restricted_industries',
    'Portal URL': 'portal_url',
    'Preferred Industries Doc Link': 'preferred_industries_doc_link',
    'Restricted Industries Doc Link': 'restricted_industries_doc_link',
    'Google Drive': 'drive_link',
    'Note': 'notes',
  },
};

export const SBA: LenderTypeSchema = {
  id: 'sba',
  displayName: 'SBA',
  description: 'Small Business Administration lenders',
  category: 'basic',
  tableName: 'lenders_sba',
  fields: [
    ...commonContactFields,
    ...commonLoanFields,
    {
      id: 'website',
      dbColumnName: 'website',
      displayName: 'Website',
      type: 'url',
      category: 'links',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
    },
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    {
      id: 'states_available',
      dbColumnName: 'states_available',
      displayName: 'States Available',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['max_loan_amount', 'credit_requirement', 'states_available', 'products_offered', 'website', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Website': 'website',
    'Products Offered': 'products_offered',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'States Available': 'states_available',
    'Credit Requirement': 'credit_requirement',
    'Google Drive': 'drive_link',
    'Note': 'notes',
  },
};

export const TERM_LOANS: LenderTypeSchema = {
  id: 'term-loans',
  displayName: 'Term Loans',
  description: 'Traditional bank and alternative term loan providers',
  category: 'basic',
  tableName: 'lenders_term_loans',
  fields: [
    ...commonContactFields,
    {
      id: 'submission_docs',
      dbColumnName: 'submission_docs',
      displayName: 'Submission Docs',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Docs',
    },
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    {
      id: 'timeline',
      dbColumnName: 'timeline',
      displayName: 'Timeline',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Timeline',
    },
    {
      id: 'states_available',
      dbColumnName: 'states_available',
      displayName: 'States Available',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States Available',
    },
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Product(s) Offered',
    },
    ...commonLoanFields,
    {
      id: 'use_of_funds',
      dbColumnName: 'use_of_funds',
      displayName: 'Use of Funds',
      type: 'textarea',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Use of Funds',
    },
    ...commonRestrictionFields,
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'credit_requirement', 'products_offered', 'timeline', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Submission Docs': 'submission_docs',
    'Submission Process': 'submission_process',
    'Timeline': 'timeline',
    'States Available': 'states_available',
    'Product(s) Offered': 'products_offered',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Use of Funds': 'use_of_funds',
    'Credit Requirement': 'credit_requirement',
    'Preferred Industries': 'preferred_industries',
    'Industy Restrictions': 'restricted_industries',
    'Note': 'notes',
  },
};

export const DSCR: LenderTypeSchema = {
  id: 'dscr',
  displayName: 'DSCR',
  description: 'Debt Service Coverage Ratio lenders',
  category: 'real-estate',
  tableName: 'lenders_dscr',
  fields: [
    ...commonContactFields,
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    ...commonLoanFields,
    {
      id: 'max_ltv',
      dbColumnName: 'max_ltv',
      displayName: 'Max LTV',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max LTV',
    },
    {
      id: 'rural',
      dbColumnName: 'rural',
      displayName: 'Rural',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Rural',
    },
    {
      id: 'states',
      dbColumnName: 'states',
      displayName: 'States',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States',
    },
    ...commonLinksFields.slice(0, 1), // Only drive_link
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'max_ltv', 'credit_requirement', 'states', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Submission Process': 'submission_process',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Max LTV': 'max_ltv',
    'Credit Requirement': 'credit_requirement',
    'Rural': 'rural',
    'States': 'states',
    'Drive Link': 'drive_link',
  },
};

export const EQUIPMENT: LenderTypeSchema = {
  id: 'equipment-financing',
  displayName: 'Equipment Financing',
  description: 'Equipment and asset financing providers',
  category: 'equipment',
  tableName: 'lenders_equipment_financing',
  fields: [
    {
      id: 'lender_name',
      dbColumnName: 'lender_name',
      displayName: 'Lender Name',
      type: 'text',
      required: true,
      category: 'contact',
      visible: true,
      displayInTable: true,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Lender Name',
    },
    {
      id: 'iso_rep',
      dbColumnName: 'iso_rep',
      displayName: 'ISO Rep',
      type: 'text',
      category: 'contact',
      visible: true,
      displayInTable: true,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'ISO Rep',
    },
    {
      id: 'phone',
      dbColumnName: 'phone',
      displayName: 'Phone',
      type: 'phone',
      category: 'contact',
      visible: true,
      displayInTable: true,
      displayInExpanded: true,
      searchable: false,
      csvHeader: 'Phone',
    },
    {
      id: 'email',
      dbColumnName: 'email',
      displayName: 'Email',
      type: 'email',
      category: 'contact',
      visible: true,
      displayInTable: true,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Email',
    },
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    {
      id: 'minimum_credit_requirement',
      dbColumnName: 'minimum_credit_requirement',
      displayName: 'Minimum Credit Requirement',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Minimum Credit Requirement',
    },
    {
      id: 'min_time_in_business',
      dbColumnName: 'min_time_in_business',
      displayName: 'Min Time in Business',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Min Time In Business',
    },
    ...commonLoanFields.slice(0, 2), // min and max loan
    {
      id: 'terms',
      dbColumnName: 'terms',
      displayName: 'Terms',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Terms',
    },
    {
      id: 'rates',
      dbColumnName: 'rates',
      displayName: 'Rates',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Rates',
    },
    {
      id: 'do_positions_matter',
      dbColumnName: 'do_positions_matter',
      displayName: 'Do Positions Matter',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Do Positions Matter',
    },
    {
      id: 'financing_types',
      dbColumnName: 'financing_types',
      displayName: 'Financing Types',
      type: 'textarea',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Financing Types (Restrucutre, New, Commercial, Individual)',
    },
    {
      id: 'states_restrictions',
      dbColumnName: 'states_restrictions',
      displayName: 'States Restrictions',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States Restrictions',
    },
    {
      id: 'preferred_equipment',
      dbColumnName: 'preferred_equipment',
      displayName: 'Preferred Equipment',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Preferred Equipment',
    },
    {
      id: 'equipment_restrictions',
      dbColumnName: 'equipment_restrictions',
      displayName: 'Equipment Restrictions',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Equipment Restrictions',
    },
    {
      id: 'website',
      dbColumnName: 'website',
      displayName: 'Website',
      type: 'url',
      category: 'links',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: false,
      csvHeader: 'Website',
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'iso_rep', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'preferred_equipment', 'financing_types', 'terms', 'website', 'notes'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'ISO Rep': 'iso_rep',
    'Phone': 'phone',
    'Email': 'email',
    'Submission Process': 'submission_process',
    'Minimum Credit Requirement': 'minimum_credit_requirement',
    'Min Time In Business': 'min_time_in_business',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Terms': 'terms',
    'Rates': 'rates',
    'Do Positions Matter': 'do_positions_matter',
    'Financing Types (Restrucutre, New, Commercial, Individual)': 'financing_types',
    'States Restrictions': 'states_restrictions',
    'Preferred Equipment': 'preferred_equipment',
    'Equipment Restrictions': 'equipment_restrictions',
    'Website': 'website',
    'Note': 'notes',
  },
  isoRepField: 'iso_rep',
};

export const FIX_FLIP: LenderTypeSchema = {
  id: 'fix-flip',
  displayName: 'Fix & Flip',
  description: 'Fix and flip property financing',
  category: 'real-estate',
  tableName: 'lenders_fix_flip',
  fields: [
    ...commonContactFields,
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    ...commonLoanFields,
    {
      id: 'max_ltv',
      dbColumnName: 'max_ltv',
      displayName: 'Max LTV',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max LTV',
    },
    {
      id: 'max_ltc',
      dbColumnName: 'max_ltc',
      displayName: 'Max LTC',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max LTC',
    },
    {
      id: 'rural',
      dbColumnName: 'rural',
      displayName: 'Rural',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Rural',
    },
    {
      id: 'states',
      dbColumnName: 'states',
      displayName: 'States',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States',
    },
    ...commonLinksFields.slice(0, 1), // Only drive_link
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'max_ltv', 'max_ltc', 'credit_requirement', 'states', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Submission Process': 'submission_process',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Max LTV': 'max_ltv',
    'Max LTC': 'max_ltc',
    'Credit Requirement': 'credit_requirement',
    'Rural': 'rural',
    'States': 'states',
    'Drive Link': 'drive_link',
  },
};

export const NEW_CONSTRUCTION: LenderTypeSchema = {
  id: 'new-construction',
  displayName: 'New Construction',
  description: 'New construction and residential development financing',
  category: 'real-estate',
  tableName: 'lenders_new_construction',
  fields: [
    ...commonContactFields,
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    ...commonLoanFields,
    {
      id: 'max_ltv',
      dbColumnName: 'max_ltv',
      displayName: 'Max LTV',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max LTV',
    },
    {
      id: 'max_ltc',
      dbColumnName: 'max_ltc',
      displayName: 'Max LTC',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max LTC',
    },
    {
      id: 'max_units',
      dbColumnName: 'max_units',
      displayName: 'Max # of Units',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Max # of Units',
    },
    {
      id: 'rural',
      dbColumnName: 'rural',
      displayName: 'Rural',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Rural',
    },
    {
      id: 'states',
      dbColumnName: 'states',
      displayName: 'States',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States',
    },
    ...commonLinksFields.slice(0, 1), // Only drive_link
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'max_ltv', 'max_ltc', 'max_units', 'credit_requirement', 'states', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Submission Process': 'submission_process',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Max LTV': 'max_ltv',
    'Max LTC': 'max_ltc',
    'Max # of Units': 'max_units',
    'Credit Requirement': 'credit_requirement',
    'Rural': 'rural',
    'States': 'states',
    'Drive Link': 'drive_link',
  },
};

export const COMMERCIAL_REAL_ESTATE: LenderTypeSchema = {
  id: 'commercial-real-estate',
  displayName: 'Commercial Real Estate',
  description: 'Commercial real estate financing',
  category: 'real-estate',
  tableName: 'lenders_commercial_real_estate',
  fields: [
    ...commonContactFields,
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Product(s) Offered',
    },
    ...commonLoanFields,
    {
      id: 'states_available',
      dbColumnName: 'states_available',
      displayName: 'States Available',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States Available',
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'credit_requirement', 'products_offered', 'states_available', 'website', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Website': 'website',
    'Product(s) Offered': 'products_offered',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'States Available': 'states_available',
    'Credit Requirement': 'credit_requirement',
    'Note': 'notes',
  },
};

export const MCA_DEBT_RESTRUCTURING: LenderTypeSchema = {
  id: 'mca-debt-restructuring',
  displayName: 'MCA Debt Restructuring',
  description: 'MCA debt restructuring and buyout providers',
  category: 'basic',
  tableName: 'lenders_mca_debt_restructuring',
  fields: [
    ...commonContactFields,
    {
      id: 'products_offered',
      dbColumnName: 'products_offered',
      displayName: 'Products Offered',
      type: 'text',
      category: 'products',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Product(s) Offered',
    },
    ...commonLoanFields,
    {
      id: 'states_available',
      dbColumnName: 'states_available',
      displayName: 'States Available',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States Available',
    },
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'credit_requirement', 'products_offered', 'states_available', 'website', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'Website': 'website',
    'Product(s) Offered': 'products_offered',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'States Available': 'states_available',
    'Credit Requirement': 'credit_requirement',
    'Note': 'notes',
  },
};

export const CONVENTIONAL_TL_LOC: LenderTypeSchema = {
  id: 'conventional-tl-loc',
  displayName: 'Conventional Bank TL/LOC',
  description: 'Conventional bank term loans and lines of credit',
  category: 'basic',
  tableName: 'lenders_conventional_tl_loc',
  fields: [
    ...commonContactFields,
    {
      id: 'states_available',
      dbColumnName: 'states_available',
      displayName: 'States Available',
      type: 'textarea',
      category: 'restrictions',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'States Available',
    },
    {
      id: 'submission_process',
      dbColumnName: 'submission_process',
      displayName: 'Submission Process',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Submission Process',
    },
    {
      id: 'docs_required',
      dbColumnName: 'docs_required',
      displayName: 'Docs Required',
      type: 'textarea',
      category: 'submission',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Docs Required',
    },
    {
      id: 'timeline',
      dbColumnName: 'timeline',
      displayName: 'Timeline',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Timeline',
    },
    {
      id: 'terms',
      dbColumnName: 'terms',
      displayName: 'Terms',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Terms',
    },
    {
      id: 'rates',
      dbColumnName: 'rates',
      displayName: 'Rates',
      type: 'text',
      category: 'terms',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Rates',
    },
    ...commonLoanFields,
    {
      id: 'banking_relationship_required',
      dbColumnName: 'banking_relationship_required',
      displayName: 'Banking Relationship Required',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Do They Need To Have a Banking Relationship To Even Be Looked At?',
    },
    {
      id: 'bank_account_opened_to_fund',
      dbColumnName: 'bank_account_opened_to_fund',
      displayName: 'Bank Account Opened to Fund',
      type: 'text',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Bank Account Has to Be Opened to Fund?',
    },
    {
      id: 'use_of_funds',
      dbColumnName: 'use_of_funds',
      displayName: 'Use of Funds',
      type: 'textarea',
      category: 'requirements',
      visible: true,
      displayInTable: false,
      displayInExpanded: true,
      searchable: true,
      csvHeader: 'Use of Funds',
    },
    ...commonRestrictionFields,
    ...commonLinksFields,
  ],
  alwaysShowColumns: ['lender_name', 'contact_person', 'phone', 'email'],
  expandableColumns: ['min_loan_amount', 'max_loan_amount', 'credit_requirement', 'terms', 'timeline', 'banking_relationship_required', 'drive_link'],
  csvHeaders: {
    'Lender Name': 'lender_name',
    'Contact Person': 'contact_person',
    'Phone': 'phone',
    'Email': 'email',
    'States Available': 'states_available',
    'Submission Process': 'submission_process',
    'Docs Required': 'docs_required',
    'Timeline': 'timeline',
    'Terms': 'terms',
    'Rates': 'rates',
    'Min Loan Amount': 'min_loan_amount',
    'Max Loan Amount': 'max_loan_amount',
    'Credit Requirement': 'credit_requirement',
    'Do They Need To Have a Banking Relationship To Even Be Looked At?': 'banking_relationship_required',
    'Bank Account Has to Be Opened to Fund?': 'bank_account_opened_to_fund',
    'Use of Funds': 'use_of_funds',
    'Preferred Industries': 'preferred_industries',
    'Industy Restrictions': 'restricted_industries',
    'Note': 'notes',
  },
};

// ============================================================================
// REGISTRY EXPORT - Maps all lender types
// ============================================================================

export const LENDER_TYPE_REGISTRY: Record<string, LenderTypeSchema> = {
  'business-line-of-credit': BUSINESS_LINE_OF_CREDIT,
  'mca': MCA,
  'sba': SBA,
  'term-loans': TERM_LOANS,
  'dscr': DSCR,
  'equipment-financing': EQUIPMENT,
  'fix-flip': FIX_FLIP,
  'new-construction': NEW_CONSTRUCTION,
  'commercial-real-estate': COMMERCIAL_REAL_ESTATE,
  'mca-debt-restructuring': MCA_DEBT_RESTRUCTURING,
  'conventional-tl-loc': CONVENTIONAL_TL_LOC,
};

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

export function getLenderTypeSchema(typeId: string): LenderTypeSchema | null {
  return LENDER_TYPE_REGISTRY[typeId] || null;
}

export function getAllLenderTypes(): LenderTypeSchema[] {
  return Object.values(LENDER_TYPE_REGISTRY);
}

export function getLenderTypesByCategory(category: string): LenderTypeSchema[] {
  return Object.values(LENDER_TYPE_REGISTRY).filter(type => type.category === category);
}

export function getFieldDefinition(typeId: string, fieldId: string): FieldDefinition | null {
  const schema = getLenderTypeSchema(typeId);
  return schema ? schema.fields.find(f => f.id === fieldId) || null : null;
}
