-- Seed MCA lenders from CSV

INSERT INTO lenders_mca (
  lender_name,
  paper,
  website,
  iso_rep,
  phone,
  email,
  submission_docs,
  submission_type,
  submission_process,
  minimum_credit_requirement,
  minimum_monthly_revenue,
  max_nsf_negative_days,
  minimum_daily_balances,
  minimum_time_in_business,
  minimum_loan_amount,
  max_loan_amount,
  terms,
  positions,
  buyouts,
  products_offered,
  states_restrictions,
  preferred_industries,
  restricted_industries,
  google_drive,
  note,
  status
) VALUES
-- Credibly
(
  'Credibly',
  'A Paper',
  'Link',
  'Gerard Snyder',
  '(248)-329-0894',
  'gsnyder@retailcapital.com',
  '4 Months Statements and App',
  'Online Portal',
  'Submit Through Client Portal',
  550,
  '$20,000',
  '7',
  '$1,000',
  '6 Months',
  '$5,000',
  '$600,000',
  '3-24 Months (Daily and Weekly)',
  '1st Only',
  '2 Positions (Must net 50%)',
  'MCA',
  'CO, DE, GA, MI, MT, NV, NJ, ND, OK, OR, SD, TX, VT',
  'Food and Service Industry, Liquor Stores, Healthcare Industry, Gas Stations, Auto Repair Shops, Beauty and Nail Salons, Grocery Stores, Hotels and Motels',
  'Adult Entertainment, Air Transport, Automotive Dealers, Bail Bonds, Money/Financial Services, Cannabis, Casinos, Non-Profit, Class 3 Weapons, Attorneys, Credit Repair, Dating Services, Dickey''s BBQ Franchises, House Flippers, Intangible Assets, Multi-level Marketing, Oil and Gas, Solar, Trucking, Vape Shops',
  'Google Drive',
  '',
  'active'
),
-- Rapid
(
  'Rapid',
  'A Paper',
  'Link',
  'Sean Costello + Deal Advisor',
  '(240)-619-8350',
  'seancostello@rapidfinance.com',
  '3 Months Bank Statements and App',
  'Online Portal',
  'Submit through Online Portal',
  600,
  '$10,000',
  '7 Days in 2 Months',
  '5x Weekly Debt Obligation',
  '2 Years',
  '$5,000',
  '$600,000',
  '4-18 Months',
  '1st Only',
  '2 Positions (Must net 35%)',
  'LOC / MCA / Term Loan',
  'CA, CT, VA',
  'Construction, Health Services, Restaurants, Retail, Business Services',
  'Adult, Auto-dealers, Trucking, Law Firms, Marijuana, Real Estate, Collection Agencies Full List',
  'Google Drive',
  '',
  'active'
),
-- Fundworks
(
  'Fundworks',
  'A Paper / B Paper',
  'Link',
  'Chris Weiner',
  '(484)-273-0721',
  'cweiner@thefundworks.com',
  '4 Bank Statements and App',
  'Email',
  'newdeals@thefundworks.com, cweiner@thefundworks.com',
  550,
  '$10,000',
  '8 in last 30 Days, 10 in last 60 days',
  '$1,000',
  '12 Months',
  '$5,000',
  '$500,000',
  'Max of 12 Months (Daily and Weekly)',
  '1st / 2nd',
  '1st-3rd (Does not have to net capital)',
  'MCA',
  'AR',
  'Restaurants, Spa/ Med Spa, Nail Shops, Chiropractic, Accountants/ Consultants, Auto Repair, Daycare, Cleaners, Plumbers/ HVAC....',
  'Adult, Law Offices, Bail Bonds, Collection Agencies, Credit Counseling, Debt Consolidation, Firearm, Money Services, Real Estate Investment or Development, Trucking....',
  'Google Drive',
  '',
  'active'
),
-- TMRnow
(
  'TMRnow',
  'A Paper / B Paper',
  'Link',
  'Scott Platto',
  '(908)-340-9454',
  'scott@tmrnow.com',
  '4 Bank Statements and App',
  'Email',
  'uw@tmrnow.com, scott@tmrnow.com + Subject Line = Only The biz name',
  550,
  '$10,000',
  '5',
  '$2,000',
  '3 Months',
  '$20,000',
  '$1,000,000',
  '2-12 Months (Daily, Weekly and Bi-Weekly)',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA',
  'N/A',
  'Restaurants, Medical, Retail',
  'Attorneys, Adult Entertainment, Other Lenders',
  'Google Drive',
  '',
  'active'
),
-- TVT Capital
(
  'TVT Capital',
  'A Paper / B Paper',
  'Link',
  'Christian Marini',
  '(516)-356-2796',
  'christian@tvtcapital.com',
  '3 Bank Statements and App',
  'Email',
  'christian@tvtcapital.com + Subject Line = New Deal - (Biz Name)',
  550,
  '$20,000',
  '5',
  '$2,000',
  '1 Year',
  '$75,000',
  '$20,000,000',
  '1-24 Months (Daily, Weekly, Bi-Weekly and Monthly Payments)',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA / SBA Bridge / Equipment Financing / Real Estate',
  'N/A',
  '',
  '',
  'Google Drive',
  '',
  'active'
),
-- Fintegra
(
  'Fintegra',
  'A Paper / B Paper',
  'Link',
  'Jackie Santos',
  '(929)-442-6551',
  'jackies@getfintegra.com',
  '3 Bank Statements and App',
  'Email',
  'submissions@getfintegra.com, jackies@getfintegra.com',
  550,
  '$10,000',
  '5',
  '$1,000',
  '1 Year',
  '$10,000',
  '$250,000',
  '8-15 Months (Daily and Weekly)',
  '1st / 2nd / 3rd',
  'Full and Partial Consolidations',
  'MCA /Flexdraw',
  'TX',
  'Medical, Healthcare, Pharmacies, Therapists, Urgent Care Clinics, Bakeries, Bars/Clubs, Beet/Wine/Liquor Stores, Cannabis, Commercial Cleaning, Government Contractors, IT and Telecom Services, Manufacturing',
  'Law Firms, Auto Dealers, Financial Services, Furniture Retailers, Real Estate, Trucking, Nail Salons, Gambling and Gaming, Non-Profits',
  'Google Drive',
  '',
  'active'
),
-- Fresh Funding
(
  'Fresh Funding',
  'A Paper / B Paper',
  'Link',
  'Adem',
  '(917) 676-6337',
  'adem@gofreshfunding.com',
  '3 Bank Statements and App',
  'Email',
  'adem@gofreshfunding.com + submissions@gofreshfunding.com Subject Line = New Deal - (Biz Name)',
  600,
  '$50,000',
  '2',
  '$3,000 / 4x the daily payment amount',
  '1.5 Years',
  '$10,000',
  '$1,000,000',
  '5-12 Months (Daily and Weekly)',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA',
  'TX',
  'Manufacturing, Retail, Business Services, Medical',
  'Adult, Firearm, Non-Profit, Law Firms, Jewelers, Financial Services, Debt Consolidation and More in Drive',
  'Google Drive',
  'Less than $50k Tax Debt last 2 years',
  'active'
),
-- Fintap
(
  'Fintap',
  'B Paper',
  'Link',
  'Danny Acevedo',
  '(617)-735-7846',
  'dacevedo@fintap.com',
  '3 Bank Statements and App',
  'Email',
  'submissions@fintap.com, dacevedo@fintap.com',
  650,
  '$20,000',
  '2',
  '$1,200 / 6-12% Monthly Revenue',
  '4 Years for 1st Position / 2 years for 2nd or 3rd Position',
  '$20,000',
  '$1,000,000',
  '24-48 Weeks (Daily and Weekly)',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA',
  'VA and MO Require ISO Registration',
  'Healthcare, Manufacturing, Restaurants, Marketing',
  'Non-Profits, Auto Sales, Legal Services, Financial Services, Cannabis (THC Products Only)',
  'Google Drive',
  '',
  'active'
),
-- Legend Advance
(
  'Legend Advance',
  'B Paper',
  'Link',
  'Bianca Rivadeneira',
  '(786)-685-3871',
  'biancar@legendfunding.com',
  '3 Bank Statements and App',
  'Email',
  'Apps@legendfunding.com, biancar@legendfunding.com',
  550,
  '$30,000 / $50,000 for High Risk',
  '4',
  '$1,000',
  '12 Months',
  '$20,000',
  '$350,000',
  '3-12 Months (Daily and Weekly)',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA',
  'TX and CA Require ISO Registration',
  'Auto Repair, Beauty/Salon, Restaurants, Retail, Medical Offices, IT Services, HVAC, Professional Services, Online Retail/E-Commerce, Construction Support Trades',
  'Adult Entertainment, Gambling, Cannabis, Firearms, Payday Lending, Credit Repair',
  'Google Drive',
  'Extra 2 months on every offer - no questions asked',
  'active'
),
-- Mantis
(
  'Mantis',
  'C Paper / D Paper',
  'Link',
  'New Rep Per Deal',
  'Deal by deal case',
  'submissions@mantisfunding.com',
  '3 Bank Statements and App',
  'Email',
  'submissions@mantisfunding.com',
  NULL,
  '$15,000',
  '$5',
  '$500k',
  '$15k',
  '$5,500',
  '$500,000',
  '3-6 Months (Daily and Weekly)',
  '1st / 2nd / 3rd / 4th',
  '-',
  'MCA',
  'N/A',
  'Auto Sales, Lawyers, Financial Services',
  '-',
  'Google Drive',
  '',
  'active'
),
-- Emmy Capital
(
  'Emmy Capital',
  'C Paper / D Paper',
  'Link',
  'Artie Barrales',
  '(201)-675-5626',
  'artie@emmycapitalgroup.com',
  '3 Bank Statements and App',
  'Email',
  'artie@primesourcesolution.com, processing@emmycapitalgroup.com, artie@primesourcesolution.com',
  600,
  '$30,000',
  '3',
  '$250',
  '6 Months',
  '$20,000',
  '$500,000',
  '6-10 Months (Daily and Weekly)',
  '1st / 2nd / 3rd',
  '-',
  'MCA',
  'TX',
  'Medical, Trades, Restaurants, Landscaping',
  'Law Firms',
  'Google Drive',
  '',
  'active'
);
