-- Seed Business Line of Credit lenders from CSV

INSERT INTO lenders_business_line_of_credit (
  lender_name,
  bank_non_bank,
  website,
  iso_contacts,
  phone,
  email,
  submission_docs,
  submission_type,
  submission_process,
  products_offered,
  credit_requirement,
  credit_used,
  min_time_in_business,
  minimum_deposit_count,
  min_monthly_revenue_amount,
  min_avg_daily_balance,
  max_loan,
  positions,
  terms,
  payments,
  draw_fees,
  preferred_industries,
  restricted_industries,
  ineligible_states,
  drive_link,
  notes,
  status
) VALUES
-- ARF Financial (Big Deals)
(
  'ARF Financial (Big Deals)',
  'Bank',
  'Link',
  'Marie Lokmanyan',
  'Marie Cell: 310-402-1600',
  'mlokmanyan@arffinancial.com',
  'Application, 3 Months of Bank Statements + Most Recent BTR (If Applicable)',
  'Email',
  'Email: stella@arffinancial.com, apps@arffinancial.com + CC deals@hugecapitalfunding.com',
  'Multiple LOC',
  575,
  'Equifax',
  '1 month',
  5,
  '$17,000',
  '$1,500',
  '$1,500,000',
  '1st',
  '12-36 Months',
  'Weekly',
  '1 time 3% Origination First Draw',
  'Restaurants + Industry List',
  'Will not lend if not listed on Industry List',
  'N/A',
  'Google Drive',
  '',
  'active'
),
-- ARF Financial (Sub 50K)
(
  'ARF Financial (Sub 50K)',
  'Bank',
  'Link',
  'Amy Laughlin',
  'Amy Cell: 832-428-4813',
  'alaughlin@arffinancial.com',
  'Application, 3 Months of Bank Statements + Most Recent BTR (If Applicable)',
  'Email',
  'Email: alaughlin@arffinancial.com, stella@arffinancial.com, apps@arffinancial.com + CC deals@hugecapitalfunding.com',
  'Multiple LOC + Installment Loan',
  575,
  'Equifax',
  '1 month',
  5,
  '$17,000',
  '$1,500',
  '$1,500,000',
  '1st',
  '12-36 Months',
  'Weekly',
  '1 time 3% Origination First Draw',
  'Restaurants + Industry List',
  'Will not lend if not listed on Industry List',
  'N/A',
  'Google Drive',
  '',
  'active'
),
-- SmartBiz
(
  'SmartBiz',
  'Bank',
  'Link',
  'Tyler Leninger',
  'Tyler''s Cell: 512-893-7355',
  'tyler.leninger@smartbizloans.com',
  '6 Months Statements, Debt Schedule',
  'Online Portal',
  'Submit Through Online Portal',
  'Line of Credit',
  680,
  '',
  '3 Years',
  5,
  '$20,000',
  '$5,000',
  '$150,000',
  '1st',
  '24-36 Months',
  'Monthly',
  '6% Origination Fee + Flat $750 Closing Costs (No Draw Fee)',
  'Any Eligible SBA Industry',
  'Adult, Casinos, Gambling, Religious',
  'N/A',
  'Google Drive',
  '',
  'active'
),
-- Plexe
(
  'Plexe',
  'Non-Bank',
  'Link',
  'Partner Portal',
  'Company: 855-230-7755',
  'admin@plexe.co, team@plexe.co',
  'App, 4 Months Bank Statements or Plaid Connection',
  'Online Portal',
  'Submit Through Online Portal',
  'Line of Credit',
  640,
  'EQ Fico 5',
  '2 Years',
  5,
  '$30,000',
  '$10,000',
  '$250,000',
  '1st / 2nd / 3rd',
  '3-12 Months',
  'Weekly',
  '2% Draw Fee + 2% Establishment Fee: Spread Evenly over 6 months on the facility limit',
  'Anything not on Restricted Industry List.',
  'Casinos, Pharmacies and Drug Retailers, Small Arms, Money Transmission, Restaurants, Rooming/Hotels, CBD, Lawyers, Automobile Dealers, Full List',
  'NV, ND, SD, TN, Puerto Rico, Hawaii, California',
  'Google Drive',
  'No MCA Loans in last 2 months',
  'active'
),
-- Idea
(
  'Idea',
  'Non-Bank',
  'Link',
  'Amit Bero',
  '305-928-1367',
  'abero@ideafinancial.com',
  '3 Months Bank Statements and App',
  'Online Portal',
  'Portal >> New Submission. Attach 3 Bank Statements and App',
  'LOC, Term Loan',
  650,
  '',
  '3 Years',
  8,
  '$15,000',
  '$5,000',
  '$275,000',
  '1st / 2nd',
  '12-36 Months',
  'Weekly Or Monthly',
  '2.49%',
  'Medical, Commercial Construction, Trades, Law Firms',
  'Schools, Farms, Real Estate, Residential Remodeling, Oil & Gas, Full List',
  'VT, ND, SD, TN, PR, HI, CA',
  'Google Drive',
  'LOC can be 2nd Position. Loan has to be first Position',
  'active'
),
-- Rapid
(
  'Rapid',
  'Non-Bank',
  'Link',
  'Sean Costello + Deal Advisor',
  '240-619-8350',
  'seancostello@rapidfinance.com',
  '3 Months Bank Statements and App',
  'Online Portal',
  'Submit through Online Portal',
  'LOC, Term Loan, MCA',
  600,
  '',
  '2 Years',
  3,
  '$10,000',
  '$5000 (Weekly Obligation)',
  '$100,000',
  '1st / 2nd / 3rd',
  '12 Months',
  'Weekly',
  '4% Draw fee',
  'Construction, Health Services, Restaurants, Retail, Business Services',
  'Adult, Auto-dealers, Trucking, Law Firms, Marijuana, Real Estate, Collection Agencies Full List',
  'NJ, MT, NV, ND, RI, SD, VT',
  'Google Drive',
  '',
  'active'
);
