-- Add Kalamata to lenders_mca table
INSERT INTO lenders_mca (
  lender_name,
  iso_rep,
  phone,
  email,
  submission_docs,
  submission_type,
  submission_process,
  minimum_credit_requirement,
  minimum_monthly_revenue,
  max_nsf_negative_days,
  minimum_daily_balances,
  minimum_time_in_business,
  minimum_loan_amount,
  max_loan_amount,
  terms,
  positions,
  buyouts,
  products_offered,
  states_restrictions,
  website,
  google_drive,
  notes,
  preferred_industries,
  restricted_industries,
  status,
  relationship,
  created_by
) VALUES (
  'Kalamata',
  'Amy Erlich',
  '(305)-213-7597',
  'amy.erlich@kalamatacapitalgroup.com',
  '4 Bank Statements and App',
  'Email',
  'deals@kalamatacapitalgroup.com, amy.erlich@kalamatacapitalgroup.com',
  '600',
  '$20k 1st $30k 2nd $35k 3rd',
  '7',
  '$1K',
  '12 Months',
  '$10,000',
  '$500,000',
  '6-18 Months',
  '1st / 2nd / 3rd',
  '2 Positions (Must net 50%)',
  'MCA',
  'N/A',
  'https://www.kalamatacapitalgroup.com/',
  'Google Drive',
  'A Paper',
  'E-commerce, Manufacturing, Medical, Restaurants, Retail Stores',
  'Adult, Agriculture, Auto Sales, Education, Farming, Gas & Oil, Gas Stations, Marijuana, Pawn Shops, Precious Metals, Religious, Transportation',
  'active',
  'Huge Capital',
  'Claude Code - Manual Import'
);
